name: cs486-midterm

services:
  frontend:
    build: ./frontend/
    ports:
      - "3001:3001"
    depends_on:
      backend:
        condition: service_started
  backend:
    build: ./backend/
    ports:
      - "8081:8081"
    environment:
      FRONTEND: ${FRONTEND}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: --default-authentication-plugin mysql_native_password
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      timeout: 10s
      interval: 1s
      retries: 10
